### PR TITLE
Remove PreControl block.

### PR DESCRIPTION
**Pull request by thomascalvert-xlnx**
Discussed in the 17-Oct-2022 meeting (amongst other changes) and no objections that I can recall.

Comments about the way decryption is handled will need to be rewritten in a subsequent change if/when we rework the placement of accelerators (aka inline externs).

### CODE REVIEW

**Comment by thantry** [comment]
LGTM. I'm guessing support for this architecture will follow in the DPDK backend?

**Review by mariobaldi — APPROVED** [review]
Looks good

**Review by jafingerhut — APPROVED** [review]
LGTM

**Comment by roop-nvda** [comment]
LGTM

**Pull request merged**
